# Creëer je Copernica Database
Copernica werkt met databases die je zelf kunt configureren. Databases zijn het centrale punt binnen Copernica, email is belangrijk maar je moet wel weten naar wie je wilt versturen. In een database worden alle klanten opslagen die jij als gebruiker gaat mailen, deze klanten binnen de database worden profielen genoemd. 

## Profielen
Een profiel kan een persoon of bedrijf zijn, dit hangt af of je een B2B of B2C bent. Je kan als gebruiker zelf bepalen welke data een profiel kan bevatten, dit wordt gedaan door de structuur van de database aan te passen met zogenoemde databasevelden. Copernica zet ook informatie in de profielen uit je database, zoals clicks, opens en errors van ontvangen campagnes. 


## Multidimensionale databases
Binnen Copernica is het mogelijk om een extra laag aan je database toe te voegen. Deze extra laag zit gekoppeld aan de profielen, denk hierbij aan de aankoophistorie van een klant of de bekeken producten van een klant. Een database die onder een profiel hangt wordt een collectie genoemd. 

## Database aanmaken Marketing Suite
In de Marketing Suite kan een database aangemaakt worden in het **Database & Profielen** gedeelte. Klik op het plusteken in de linkerbovenhoek. Klik op Database en geef de database een naam. 

Het maakt niet uit of een database in de Publisher of Marketing suite gemaakt is, dit is dezelfde database. Als een aanpassing in de Publisher gedaan wordt, dan is deze ook zichtbaar in de Marketing Suite. Nadat de database aangemaakt is, is de volgende stap is structuur aan je database geven door databasevelden toe te voegen.

## Database aanmaken Publisher
Binnen de Publisher kan een database aangemaakt worden via **Databasebeheer > Nieuwe database aanmaken**. In het venster hierna kan een naam gegeven worden aan de database. De nieuw aangemaakte database verschijnt in het venster aan de linkerkant, boven dit venster staat **Databases en selecties**. Via dit venster kan de database geselecteerd worden en kunnen de profielen in de database bekeken worden. 

Het maakt niet uit of een database in de Publisher of Marketing suite gemaakt is, dit is dezelfde database. Als een aanpassing in de Marketing Suite gedaan wordt, dan is deze ook zichtbaar in de Publisher. Nadat de database aangemaakt is, is de volgende stap is structuur aan je database geven door databasevelden toe te voegen.

## Profiel aanmaken Marketing Suite
Klik op het poppetje met het plusje, vul vervolgens de waardes in die in het profiel dienen te komen en druk op verzenden. 

## Profiel aanmaken Publisher
Klik op **profiel > Nieuw profiel aanmaken**, vul vervolgens de waardes in die in het profiel dienen te komen en druk op opslaan. 

